services:
  - type: worker
    name: terabox-userbot
    env: python
    region: oregon
    plan: free
    repo: https://github.com/avidaksh06/Terabox-downloader-stranger-x-bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "apt-get update && apt-get install -y ntpdate && ntpdate -u time.google.com && python3 main.py"
    envVars:
      - key: API_ID
        value: ${API_ID}
      - key: API_HASH
        value: ${API_HASH}
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: SESSION_NAME
        value: ${SESSION_NAME}
      - key: ADMINS
        value: ${ADMINS}
      - key: TMP_DIR
        value: ./tmp
